name: Git action
on: push
jobs:
    First-job:
        runs-on: ubuntu-latest
        steps:
            - name: print welcom
              run: echo"welcome sir in ${{ runner.os }} doing ${{ github.event_name }}"
            - name: Check out repository code action
              uses: actions/checkout@v4
            - run: echo " Cloning The ${{ github.repository }} repository "
            - name: List files in the repository
              run: ls ${{ github.workspace }}

